clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:

  run-tests:
    image: gwiq/sbt-docker:latest
    volumes:
      - /var/lib/docker/sbt:/cache
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=/cache/.coursier -Dsbt.ivy.home=/cache/.ivy2 -Divy.home=/cache/.ivy2 -Dfile.encoding=utf-8 -Dsbt.gigahorse=false test
    secrets: [ aws_access_key_id, aws_secret_access_key, aws_region ]
    when:
      event: push

  publish-maven-artifacts:
    image: gwiq/sbt-docker:latest
    volumes:
      - /var/lib/docker/sbt:/cache
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=/cache/.coursier -Dsbt.ivy.home=/cache/.ivy2 -Divy.home=/cache/.ivy2 -Dfile.encoding=utf-8 druid4s-utils/publish druid4s-client/publish
    secrets: [ bintray_user, bintray_pass, aws_access_key_id, aws_secret_access_key, aws_region ]
    when:
      event: [deployment, tag]
