kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 50
    tags: true

- name: run-tests
  pull: default
  image: lustefaniak/sbt:graalvm11_1.3.4_2.13.1
  commands:
  - "echo $TEST_CREDENTIALS > $GOOGLE_APPLICATION_CREDENTIALS"
  - sbt -color=always -mem 1024 -Dsbt.ivy.home=/cache/.ivy2 -Divy.home=/cache/.ivy2 -Dfile.encoding=utf-8 test
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    BROKER_HOST: "druid-broker.qpipeline-s-0.gcp.in.globalwebindex.com"
    OVERLORD_HOST: "druid-overlord.qpipeline-s-0.gcp.in.globalwebindex.com"
    COORDINATOR_HOST: "druid-coordinator.qpipeline-s-0.gcp.in.globalwebindex.com"
    TEST_CREDENTIALS:
      from_secret: sa_qpipeline_s
  volumes:
  - name: sbt
    path: /cache
  when:
    event:
    - push

- name: publish-maven-artifacts
  pull: default
  image: lustefaniak/sbt:graalvm11_1.3.4_2.13.1
  commands:
  - sbt -color=always -Dsbt.ivy.home=/cache/.ivy2 -Divy.home=/cache/.ivy2 -Dfile.encoding=utf-8 +druid4s-utils/publish +druid4s-client/publish
  environment:
    BINTRAY_PASS:
      from_secret: bintray_pass
    BINTRAY_USER:
      from_secret: bintray_user
  volumes:
  - name: sbt
    path: /cache
  when:
    event:
    - promote
    - tag

volumes:
- name: sbt
  host:
    path: /var/lib/docker/sbt