version: '2'
services:

    druid:
      image: gwiq/imply-base:1.3.1
      restart: "no"
      environment:
        - COMMON_DRUID_S3_ACCESSKEY=???
        - COMMON_DRUID_S3_SECRETKEY=???
        - COMMON_DRUID_ZK_SERVICE_HOST=localhost
        - COMMON_DRUID_METADATA_STORAGE_TYPE=derby
        - COMMON_DRUID_METADATA_STORAGE_CONNECTOR_HOST=localhost
        - COMMON_DRUID_METADATA_STORAGE_CONNECTOR_PORT=1527
        - COMMON_DRUID_METADATA_STORAGE_CONNECTOR_CONNECT_URI=jdbc:derby://localhost:1527/var/druid/metadata.db;create=true
        - COMMON_DRUID_METADATA_STORAGE_USER=app
        - COMMON_DRUID_METADATA_STORAGE_PSWD=derby
        - COMMON_DRUID_STORAGE_TYPE=local
        - COMMON_DRUID_STORAGE_DIRECTORY=var/druid/segments
        - COMMON_DRUID_STORAGE_BUCKET=???
        - COMMON_DRUID_STORAGE_BASEKEY=???
        - COMMON_DRUID_EMITTER=noop
        - COMMON_DRUID_EMITTER_LOGGING_LOGLEVEL=warn
        - COMMON_DRUID_EMITTER_GRAPHITE_HOSTNAME=???
        - COMMON_DRUID_EMITTER_GRAPHITE_PORT=2004
        - COMMON_DRUID_CACHE_SIZEINBYTES=10000000    # this is used by both historical and broker nodes !!!
        - COORDINATOR_DRUID_COORDINATOR_STARTDELAY=PT3S
        - COORDINATOR_DRUID_COORDINATOR_PERIOD=PT1S
        - COORDINATOR_DRUID_MANAGER_SEGMENTS_POLLDURATION=PT3s
        - COORDINATOR_KILL_ON=false
        - COORDINATOR_KILL_PERIOD=P1D
        - COORDINATOR_KILL_DURATION_TO_RETAIN=PT-1S
        - COORDINATOR_KILL_MAX_SEGMENTS=0
        - MIDDLE_MANAGER_DRUID_WORKER_CAPACITY=1
        - MIDDLE_MANAGER_DRUID_PEON_MEMORY=256m
        - MIDDLE_MANAGER_DRUID_HEAP_MEMORY=64m
        - HISTORICAL_DRUID_HISTORICAL_CACHE_USECACHE=false
        - HISTORICAL_DRUID_HISTORICAL_CACHE_POPULATECACHE=false
        - HISTORICAL_DRUID_CACHE_TYPE=local
        - HISTORICAL_DRUID_HEAP_MEMORY=256m
        - HISTORICAL_DRUID_DIRECT_MEMORY=196m  # this must apply [ (DRUID_PROCESSING_NUMTHREADS + 1) * DRUID_PROCESSING_BUFFER_SIZEBYTES < HISTORICAL_DRUID_DIRECT_MEMORY ]
        - BROKER_DRUID_BROKER_CACHE_USECACHE=false
        - BROKER_DRUID_BROKER_CACHE_POPULATECACHE=false
        - BROKER_DRUID_BROKER_CACHE_UNCACHEABLE=["groupBy", "select"]
        - BROKER_DRUID_HEAP_MEMORY=256m
        - BROKER_DRUID_DIRECT_MEMORY=196m  # this must apply [ (DRUID_PROCESSING_NUMTHREADS + 1) * DRUID_PROCESSING_BUFFER_SIZEBYTES < BROKER_DRUID_DIRECT_MEMORY ]
        - OVERLORD_DRUID_HEAP_MEMORY=256m
        - PIVOT_DRUID_BROKER_HOST=localhost
        - DRUID_HOST=localhost
        # note that these are used by all middlemanager, historical and broker
        - DRUID_PROCESSING_BUFFER_SIZEBYTES=67108864 # On MiddleManager this must apply [ (DRUID_PROCESSING_NUMTHREADS + 1) * DRUID_PROCESSING_BUFFER_SIZEBYTES < MIDDLE_MANAGER_DRUID_PEON_MEMORY ]
        - DRUID_PROCESSING_NUMTHREADS=1
      ports:
        - 8081:8081
        - 8082:8082
        - 8090:8090
        - 9095:9095
      volumes:
        - /tmp/druid4s-test:/tmp/druid4s-test
      command: ./interpolate-and-supervise.sh quickstart.conf
